// <auto-generated />
using System;
using HookVerse.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HookVerse.Infrastructure.Migrations
{
    [DbContext(typeof(HookVerseDbContext))]
    [Migration("20251018175018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hookverse")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HookVerse.Core.Entities.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("text");

                    b.Property<string>("ResponseBody")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("ResponseHeaders")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WebhookEventId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_DeliveryAttempts_StartedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DeliveryAttempts_Status");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("IX_DeliveryAttempts_SubscriptionId");

                    b.HasIndex("WebhookEventId")
                        .HasDatabaseName("IX_DeliveryAttempts_WebhookEventId");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("IX_DeliveryAttempts_Status_NextRetryAt");

                    b.HasIndex("WebhookEventId", "AttemptNumber")
                        .HasDatabaseName("IX_DeliveryAttempts_WebhookEventId_AttemptNumber");

                    b.ToTable("DeliveryAttempts", "hookverse");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_EventTypes_IsActive");

                    b.HasIndex("SubscriberId")
                        .HasDatabaseName("IX_EventTypes_SubscriberId");

                    b.HasIndex("Name", "Version", "SubscriberId")
                        .IsUnique()
                        .HasDatabaseName("IX_EventTypes_Name_Version_SubscriberId");

                    b.ToTable("EventTypes", "hookverse");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.SchemaDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("IX_SchemaDefinitions_ContentHash");

                    b.HasIndex("EventTypeId")
                        .IsUnique()
                        .HasDatabaseName("IX_SchemaDefinitions_EventTypeId");

                    b.ToTable("SchemaDefinitions", "hookverse");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RetentionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique()
                        .HasDatabaseName("IX_Subscribers_ApiKeyHash");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Subscribers_Email");

                    b.ToTable("Subscribers", "hookverse");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthConfig")
                        .HasColumnType("text");

                    b.Property<int>("AuthType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomHeaders")
                        .HasColumnType("text");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FilterExpression")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("IX_Subscriptions_EventTypeId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Subscriptions_IsActive");

                    b.HasIndex("SubscriberId")
                        .HasDatabaseName("IX_Subscriptions_SubscriberId");

                    b.HasIndex("EventTypeId", "IsActive")
                        .HasDatabaseName("IX_Subscriptions_EventTypeId_IsActive");

                    b.ToTable("Subscriptions", "hookverse");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PayloadSizeBytes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_WebhookEvents_CreatedAt");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("IX_WebhookEvents_EventTypeId");

                    b.HasIndex("ScheduledFor")
                        .HasDatabaseName("IX_WebhookEvents_ScheduledFor");

                    b.HasIndex("SubscriberId")
                        .HasDatabaseName("IX_WebhookEvents_SubscriberId");

                    b.HasIndex("SubscriberId", "CreatedAt")
                        .HasDatabaseName("IX_WebhookEvents_SubscriberId_CreatedAt");

                    b.ToTable("WebhookEvents", "hookverse");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.DeliveryAttempt", b =>
                {
                    b.HasOne("HookVerse.Core.Entities.Subscription", "Subscription")
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HookVerse.Core.Entities.WebhookEvent", "WebhookEvent")
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("WebhookEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("WebhookEvent");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.EventType", b =>
                {
                    b.HasOne("HookVerse.Core.Entities.Subscriber", "Subscriber")
                        .WithMany("EventTypes")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.SchemaDefinition", b =>
                {
                    b.HasOne("HookVerse.Core.Entities.EventType", "EventType")
                        .WithOne("SchemaDefinition")
                        .HasForeignKey("HookVerse.Core.Entities.SchemaDefinition", "EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.Subscription", b =>
                {
                    b.HasOne("HookVerse.Core.Entities.EventType", "EventType")
                        .WithMany("Subscriptions")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HookVerse.Core.Entities.Subscriber", "Subscriber")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.WebhookEvent", b =>
                {
                    b.HasOne("HookVerse.Core.Entities.EventType", "EventType")
                        .WithMany("WebhookEvents")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HookVerse.Core.Entities.Subscriber", "Subscriber")
                        .WithMany("WebhookEvents")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.EventType", b =>
                {
                    b.Navigation("SchemaDefinition");

                    b.Navigation("Subscriptions");

                    b.Navigation("WebhookEvents");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.Subscriber", b =>
                {
                    b.Navigation("EventTypes");

                    b.Navigation("Subscriptions");

                    b.Navigation("WebhookEvents");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.Subscription", b =>
                {
                    b.Navigation("DeliveryAttempts");
                });

            modelBuilder.Entity("HookVerse.Core.Entities.WebhookEvent", b =>
                {
                    b.Navigation("DeliveryAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
